<!doctype html>
<html lang = "en">
	<head>


			<meta charset= "utf-8">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
			<title>Assignment 2- Lagos by Fiyinfoluwa Oluyinka, Olatunde Oshunlaja, Prosper Feya </title>
			 <link rel="stylesheet" type="text/css" href="css/hero.css">
			 <link rel="stylesheet" type="text/css" href="css/style.css"> 
			 <link rel="stylesheet" type="text/css" href="css/navigation.css">
			 <link rel="stylesheet" href="sss/sss.css">
			 <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">


</head>